version: "3.7"
services:
  demo:
    image: gaetancollaud/kafka-demo
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=spring
#      - SPRING_PROFILES_ACTIVE=raw

  kafka:
    image: johnnypark/kafka-zookeeper
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_HOST=${ADVERTISED_HOST}

